name: Update Service Image Tag

on:
  repository_dispatch:
    types: [update-docker-tag]

jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update image tag in docker-compose.yml
        run: |
          FILE=docker-compose.yml
          IMAGE_NAME="${{ github.event.client_payload.image_name }}"
          NEW_TAG="${{ github.event.client_payload.new_tag }}"

          # Extract base name without tag (if needed)
          BASE_NAME=$(echo "$IMAGE_NAME" | cut -d: -f1)

          # Replace the line that starts with image: and set it to the new tag
          sed -i "s|^\([[:space:]]*image:[[:space:]]*\)${BASE_NAME}:[^[:space:]]*|\1${BASE_NAME}:${NEW_TAG}|" "$FILE"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docker-compose.yml
          git commit -m "Update ${SERVICE_NAME} image tag to ${{ github.event.client_payload.new_tag }}"
          git push